(() => {
  const config = window.PROTOTYPE_CONFIG || {};
  const catalog = [
    {id:'sales',icon:'↗',name:'Sales Agent',industries:['all'],summary:'Qualifies opportunities, researches prospects and keeps every follow-up moving.',mcps:['HubSpot','Salesforce','Gmail','Slack','LinkedIn'],outcomes:['Research every new lead automatically','Score and prioritise opportunities','Draft outreach in your company voice','Schedule timely follow-ups','Keep your CRM records current']},
    {id:'documents',icon:'▤',name:'Document Agent',industries:['professional-services','legal','construction','all'],summary:'Turns briefs and source material into polished documents using your templates.',mcps:['Google Drive','Microsoft 365','Notion','Dropbox','Slack'],outcomes:['Create proposals from approved templates','Summarise long source documents','Prepare client-ready reports','Maintain consistent tone and branding','Route drafts for human approval']},
    {id:'invoices',icon:'$',name:'Invoice Agent',industries:['professional-services','retail','construction','all'],summary:'Reads invoices, checks records, flags anomalies and prepares approvals.',mcps:['Xero','MYOB','QuickBooks','Gmail','Google Drive'],outcomes:['Capture invoice data automatically','Match invoices to business records','Flag duplicates and unusual amounts','Prepare approval queues','Produce scheduled finance summaries']},
    {id:'support',icon:'◉',name:'Support Agent',industries:['retail','healthcare','technology','all'],summary:'Triages customer enquiries, drafts helpful replies and escalates what matters.',mcps:['Zendesk','Intercom','Gmail','Slack','Microsoft Teams'],outcomes:['Classify every inbound enquiry','Draft replies in your support voice','Surface urgent or sensitive cases','Find answers from your knowledge base','Track recurring customer issues']},
    {id:'website',icon:'◇',name:'Website Agent',industries:['all'],summary:'Keeps website content accurate, on-brand and ready for approval before publishing.',mcps:['GitHub','Webflow','WordPress','Google Drive','Slack'],outcomes:['Draft new website pages','Update approved copy and details','Check pages for stale information','Prepare search-friendly metadata','Publish only after human approval']},
    {id:'operations',icon:'✓',name:'Operations Agent',industries:['professional-services','construction','healthcare','all'],summary:'Coordinates repeatable workflows and keeps teams informed when work changes state.',mcps:['Monday.com','Asana','Notion','Slack','Microsoft Teams'],outcomes:['Turn requests into structured work','Monitor deadlines and blockers','Prepare daily operating summaries','Chase missing information','Escalate exceptions to the right person']}
  ];
  const state = {step:0,name:'',design:'ocean'};
  const root = document.getElementById('prototype-app');
  const designs = [{id:'ocean',label:'Ocean',className:''},{id:'sunset',label:'Sunset',className:'sunset'},{id:'mint',label:'Mint',className:'mint'}];
  const company = config.company || 'Your Company';
  const industry = config.industry || 'professional-services';

  const button = (label, action, secondary=false) => `<button class="btn ${secondary?'btn-secondary':'btn-primary'}" data-action="${action}">${label}</button>`;
  const bot = (extra='') => `<div class="bot ${extra}" role="img" aria-label="Friendly agent design"></div>`;
  const layout = content => `<main class="shell"><header class="topbar"><div class="brand"><img src="/square_logo.png" alt=""><span>Agent Hatchers</span></div><span class="private-pill">Private prototype for ${escapeHtml(company)}</span></header><section class="panel"><div class="progress" aria-label="Prototype progress"><span style="--progress:${Math.min(100,(state.step+1)/6*100)}%"></span></div><div class="step-label">Step ${state.step+1} of 6</div>${content}</section></main>`;
  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function render(){
    const screens = [welcome,nameScreen,designScreen,hatchScreen,revealScreen,marketScreen];
    root.innerHTML = layout(screens[state.step]());
    bind();
  }
  function welcome(){return `<div class="stage welcome-grid"><div><span class="eyebrow">Made for ${escapeHtml(company)}</span><h1>Meet the agent your business has been waiting for.</h1><p class="lead">This private experience is tailored to ${escapeHtml((config.industryLabel||'your industry').toLowerCase())}. Together, we’ll name your first agent, choose how it looks and watch it hatch.</p><div class="actions">${button('Start hatching →','next')}</div></div><div class="welcome-art" aria-hidden="true"><div class="preview-egg"></div></div></div>`;}
  function nameScreen(){return `<div class="stage"><span class="eyebrow">Step 1 · Give it an identity</span><h2>What should your first agent be called?</h2><p>Choose a name your team will enjoy seeing in Slack, Teams or Hermes.</p><input class="name-field" id="agent-name" maxlength="28" autocomplete="off" placeholder="e.g. Pip, Scout or Atlas" value="${escapeHtml(state.name)}" aria-label="Agent name"><div class="actions">${button('Back','back',true)}${button('Choose a design →','save-name')}</div></div>`;}
  function designScreen(){return `<div class="stage"><span class="eyebrow">Step 2 · Choose a design</span><h2>How should ${escapeHtml(state.name)} look?</h2><p>Pick a starting personality. Your final agent can be refined with your company colours and branding.</p><div class="design-grid">${designs.map(d=>`<button class="design-card ${state.design===d.id?'selected':''}" data-design="${d.id}" aria-pressed="${state.design===d.id}">${bot(d.className)}<strong>${d.label}</strong></button>`).join('')}</div><div class="actions">${button('Back','back',true)}${button(`Hatch ${escapeHtml(state.name)} →`,'hatch')}</div></div>`;}
  function hatchScreen(){return `<div class="stage hatch-zone"><span class="eyebrow">Hatching your agent</span><h2>Something helpful is coming to life…</h2><div class="egg" id="egg" aria-label="Agent egg hatching"></div><p>Loading ${escapeHtml(company)} context, tools and personality.</p></div>`;}
  function revealScreen(){const d=designs.find(x=>x.id===state.design);return `<div class="stage hatch-zone"><span class="eyebrow">Your agent has hatched</span><div class="hatched">${bot(d?.className||'')}<h1>Hello, ${escapeHtml(state.name)}!</h1><p class="lead" style="margin-inline:auto">Your first agent is ready. Now let’s meet the specialist agents recommended for ${escapeHtml(company)}.</p><div class="actions" style="justify-content:center">${button('Explore your marketplace →','market')}</div></div></div>`;}
  function marketScreen(){const recommended = new Set(config.recommendedAgents||[]);const agents=catalog.filter(a=>a.industries.includes(industry)||recommended.has(a.id));return `<div class="stage"><div class="market-head"><div><span class="eyebrow">${escapeHtml(config.industryLabel||'Industry')} marketplace</span><h2>Build your agent team</h2><p>Scroll through recommended agents. Select one to see its MCP connections and five concrete outcomes.</p></div>${button('Start again','reset',true)}</div>${agents.length?`<div class="market-row">${agents.map(agent=>`<article class="agent-card"><div class="agent-icon">${agent.icon}</div><h3>${agent.name}</h3><p>${agent.summary}</p><div>${agent.mcps.slice(0,3).map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="actions"><button class="btn btn-primary" data-agent="${agent.id}">View agent</button></div></article>`).join('')}</div>`:'<div class="empty">No recommendations have been configured yet.</div>'}</div>`;}
  function showAgent(id){const agent=catalog.find(a=>a.id===id);if(!agent)return;const backdrop=document.createElement('div');backdrop.className='modal-backdrop';backdrop.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="agent-title"><div class="modal-top"><div><span class="eyebrow">Agent profile</span><h2 id="agent-title">${agent.name}</h2></div><button class="close" aria-label="Close agent profile">×</button></div><p>${agent.summary}</p><h3>What this agent can do for ${escapeHtml(company)}</h3><div class="checks">${agent.outcomes.map(o=>`<div class="check"><i>✓</i><span>${o}</span></div>`).join('')}</div><h3>Available MCP connections</h3><p>These secure connectors let the agent work with your existing systems while respecting approvals and permissions.</p><div class="mcp-list">${agent.mcps.map(m=>`<span class="mcp">${m}</span>`).join('')}</div></section>`;document.body.appendChild(backdrop);const close=()=>backdrop.remove();backdrop.querySelector('.close').onclick=close;backdrop.onclick=e=>{if(e.target===backdrop)close()};document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}},{once:true});}
  function celebrate(){const c=document.createElement('div');c.className='confetti';for(let i=0;i<38;i++){const s=document.createElement('span');s.style.left=`${Math.random()*100}%`;s.style.background=['#216bac','#c1dce8','#ffb36b','#59c6ad'][i%4];s.style.animationDelay=`${Math.random()*.5}s`;c.appendChild(s)}document.body.appendChild(c);setTimeout(()=>c.remove(),2400)}
  function bind(){root.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{const a=el.dataset.action;if(a==='back'){state.step=Math.max(0,state.step-1);render()}if(a==='next'){state.step++;render()}if(a==='save-name'){const input=document.getElementById('agent-name');state.name=input.value.trim();if(!state.name){input.focus();input.setAttribute('aria-invalid','true');return}state.step++;render()}if(a==='hatch'){state.step=3;render();requestAnimationFrame(()=>document.getElementById('egg')?.classList.add('crack'));setTimeout(()=>{state.step=4;render();celebrate()},1700)}if(a==='market'){state.step=5;render()}if(a==='reset'){state.step=0;state.name='';render()}});root.querySelectorAll('[data-design]').forEach(el=>el.onclick=()=>{state.design=el.dataset.design;render()});root.querySelectorAll('[data-agent]').forEach(el=>el.onclick=()=>showAgent(el.dataset.agent));const input=document.getElementById('agent-name');if(input)input.onkeydown=e=>{if(e.key==='Enter')root.querySelector('[data-action="save-name"]').click()};}
  render();
})();
